// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Authenticated } from "../../../handshake/schema/Authenticated";
import type { RegisterForm } from "../../../handshake/schema/RegisterForm";

export interface __Endpoint_register { in_type: RegisterForm, out_data_type: Authenticated, query_type: null, }