// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Authenticated } from "../../../handshake/schema/Authenticated";
import type { LoginForm } from "../../../handshake/schema/LoginForm";

export interface __Endpoint_login { in_type: LoginForm, out_data_type: Authenticated, query_type: null, }