// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ValidationError { code: string, message: string | null, params: Record<string, string>, }