
// This file was generated by [papi]. Do not edit this file manually.

import { type Response, request_inner } from '$lib/http/response';
const method = 'delete'; 
const host = import.meta.env.VITE_API_URL?? ''; 
import type { __Endpoint_delete as DELETE } from '$lib/endpoint_defines//users/{username}/DELETE'; 
export default async function delete(in_val: DELETE['in_type'], username: string,searchParams?: URLSearchParams): Promise<Response<DELETE['out_data_type']>> {
  const params = searchParams?? new URLSearchParams();
	const request_init: RequestInit = {
        credentials: 'same-origin',
		method: method,
		headers: {},
	}
  const path = '//users/' + username + ''

  for (const key in in_val) {
    params.set(key, in_val[key]);
  }
    
	return request_inner(host, path, params, request_init);
}
  