// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface __Endpoint_index { in_type: null, out_data_type: null, query_type: null, }