// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoginFormEmail } from "./LoginFormEmail";
import type { LoginFormUsername } from "./LoginFormUsername";

export type LoginForm = { "login_type": "username" } & LoginFormUsername | { "login_type": "email" } & LoginFormEmail;