// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface User { username: string, email: string, is_verified: boolean, last_login: string, }