// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { User } from "../../../handshake/schema/User";

export interface __Endpoint_get_user { in_type: null, out_data_type: User, query_type: null, }