
// This file was generated by [papi]. Do not edit this file manually.

import { type Response, request_inner } from '$lib/http/response';
const method = 'get'; 
const host = import.meta.env.VITE_API_URL?? ''; 
import type { __Endpoint_index as GET } from '$lib/endpoint_defines//GET'; 
export default async function get(in_val: GET['in_type'],searchParams?: URLSearchParams): Promise<Response<GET['out_data_type']>> {
  const params = searchParams?? new URLSearchParams();
	const request_init: RequestInit = {
        credentials: 'same-origin',
		method: method,
		headers: {},
	}
  const path = '/'

  for (const key in in_val) {
    params.set(key, in_val[key]);
  }
    
	return request_inner(host, path, params, request_init);
}
  