// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DbRange } from "../../handshake/DbRange";
import type { User } from "../../handshake/schema/User";

export interface __Endpoint_get_all_users { in_type: null, out_data_type: Array<User>, query_type: DbRange, }