// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Direction } from "./Direction";

export interface DbRange { limit: number | null, offset: number | null, search: string | null, order_by: string | null, direction: Direction | null, }