// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Error } from "./Error";
import type { Validation } from "./Validation";

export type ErrorResponseKind = { "err_kind": "list", "response": Array<Error> } | { "err_kind": "single", "response": Error } | { "err_kind": "validation", "response": Validation };