// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorKind } from "./ErrorKind";
import type { ErrorOrigin } from "./ErrorOrigin";

export interface Error { kind: ErrorKind, message: string, origin: ErrorOrigin, }