// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DbRange } from "../../../../handshake/DbRange";
import type { UserPermissions } from "../../../../handshake/schema/UserPermissions";

export interface __Endpoint_get_user_permissions { in_type: null, out_data_type: UserPermissions, query_type: DbRange, }